--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OguzhanUmutlu/DynamicFT
build-by-default: true
branches:
- main
projects:
  DynamicFT:
    icon: "icon.png"
    lint:
      phpstan: false
...
